config/routes.rb
Rails.application.routes.draw do
  root to: 'todos#index'

  resources :users
  resources :todos
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, presence: true, length: { minimum: 8 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login 

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:todos)
    else
      flash.now[:danger] = 'ログイン失敗'
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to url_for(action: :new)
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all.where(user_id: current_user.id).order(id: :desc)
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.user_id = current_user.id
    if @todo.save
      redirect_to url_for(action: :index), notice: '作成に成功しました'
    else
      flash.now[:danger] = '作成に失敗しました'
      render :new
    end
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to url_for(action: :index), notice: '削除に成功しました'
  end

  private

  def todo_params
    params.require(:todo).permit(:title, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(params[:user][:email], params[:user][:password])
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TodoList
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  body
    .navbar.navbar-expand-lg.navbar-dark.bg-primary style="color: white"
      .navbar-brand 
        = link_to 'Todo List', root_path, style: "color: white"
      .collapse.navbar-collapse
        ul.navbar-nav.mr-auto
        - if logged_in?
          li.nav-item style="list-style-type: none"
            a.nav-link = current_user.name

          li.nav-item style="list-style-type: none"
            .nav-link = link_to 'ログアウト', logout_path, method: :delete, style: "color: white"
        - else
          li.navbar-item style="list-style-type: none"
             .nav-link = link_to '新規登録', new_user_path, style: "color: white"
    - flash.each do |message_type, message|
      - if message_type == "notice"
        - message_type = "success"
      .alert class= "alert-#{message_type}" = message
    = yield

app/views/todos/index.html.slim
h1 Todoリスト 

.container
  = link_to '新規追加', new_todo_path, class: 'btn btn-primary'
  ul.list-group
    - @todos.each do |todo|
      li.list-group-item
        = todo.title
        = button_to '削除', todo_path(todo.id), method: :delete, data:{confirm: '本当に削除しますか？'}, class: 'btn btn-danger float-right'
        = link_to '詳細', todo_path(todo.id), class: 'btn btn-success float-right'

app/views/todos/new.html.slim
- if @todo.errors.any?
  .alert.alert-warning
    ul
      - @todo.errors.each do |message|
        li = "#{message}が入力されていません"

.container
  = form_with model: @todo, local: true do |f|
    .form-group
      = f.label :title, 'タイトル'
      = f.text_field :title, class: 'form-control'
    .form-group
      = f.label :content, '内容'
      = f.text_area :content, class: 'form-control'
    .form-group style="width: 100%; margin-left: 58%;"
      .btn-toolbar
        = link_to todos_path, class: "btn btn-secondary btn-group", style: "width: 20%" do
          i.fas.fa-chevron-left.fa-fw
          | キャンセル

        = button_tag type: 'submit', class: "btn btn-primary btn-group", style: "width: 20%; margin-left: 2%" do
          | 追加

app/views/todos/show.html.slim
.container
  ul.list-group
    li.list-group-item
      = @todo.title
    li.list-group-item
      = @todo.content
  = link_to todos_path, class: "btn btn-secondary btn-group", style: "width: 20%" do
          i.fas.fa-chevron-left.fa-fw
          | 戻る

app/views/users/new.html.slim
= form_with model: @user, local: true, class: 'container' do |f|
  .form-group.col-sm-12
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control', placeholder: 'メールアドレス'
  .form-group.col-sm-12
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control', placeholder: '名前'
  .form-group.col-sm-12
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control', placeholder: 'パスワード'
  .form-group.col-sm-12
    = f.label :password_confirmation, 'パスワード(再入力)'
    = f.password_field :password_confirmation, class: 'form-control', placeholder: 'パスワード(再入力)'
  .form-group.col-sm-12
    = f.submit '新規登録', class: 'btn btn-primary'